<?php 

	require_once("BancoClientes.php");
	$banco = new BancoClientes();
	$cliente = $banco->getCliente($_GET['id']);
?>

<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Clientee</title>
	<link rel="stylesheet" href="css/bootstrap.css">
	<link rel="stylesheet" href="css/bootstrap.min.css">
</head>
<body>
	<div class="container">
		
		<div class="jumbotron">
			<h1>Gestão de Clientess</h1>
			<p>Exercicio da Code.Education</p>
		</div>
	
		<div class="panel panel-primary">
			<div class="panel-heading"> <span class="glyphicon glyphicon-user"></span> 		<?php echo $cliente->getNome()?> </div>

			
			<div class="panel-body">
				<?php 
				  echo "<b>Nome: </b>".$cliente->getNome()."<br>";
              	  echo "<b>Endereço: </b>".$cliente->getEndereco()."<br>";
                  echo "<b>CPF: </b>".$cliente->getCPF()."<br>";
				?>
			</div>

			<div class="panel-footer">
				<a href="index.phtml" class="btn btn-default">Voltar</a>	
			</div>

		</div>


	</div>



</body>
</html>

